# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHvOxB-enWBpA7obs97smt_URl4VSkqI
"""

import numpy as np

arr = np.array([[1.5, 2.5, np.nan],
                  [4.5, 5.5, np.nan]])

print(arr[:, ~np.isnan(arr).any(axis=0)])

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr[[0,2]])

print(arr[[1]])

print(arr[[2]])